name: Publish release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build workshop
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
      
    - name: Run workshop bundler
      run: ./release_bundler.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: "Multiplayer Compatibility"
        files: |
          Multiplayer-Compatibility.zip
